### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by saberrahul** [jpilfold/ngx-image-viewer#12]
**Expected Behavior** : Keyboard navigation should work only for focused image gallery.
**Current Behavior** : Currently when there are more then one image galleries on page, keyboard navigation changes the images for all image galleries.

**Comment by jpilfold** [comment]
Good point, I'll take a look at this now

**Comment by jpilfold** [comment]
Okay, I've merged in a fix for this issue, and published a new version to NPM. Let me know if you're happy with the change

**Comment by saberrahul** [comment]
With version 1.0.8, build is failing with below error message

ERROR in node_modules\ngx-image-viewer\ngx-image-viewer.d.ts.ImageViewerComponent.html(7,38): : Property 'loading' is private and only accessible within class 'ImageViewerComponent'.

Seems like you have to change the property 'loading' to public.

**Comment by jpilfold** [comment]
@saberrahul Have you had a chance to take a look yet? Just want to get these issues closed off if I can.

**Comment by saberrahul** [comment]
Yes, this issue is fixed and shall be closed.
Great work.
