### ISSUE TITLE
Scroll on image while zoom via wheel is disabled

### ISSUE THREAD

**Issue by saberrahul** [jpilfold/ngx-image-viewer#13]
**Expected Behavior** : If image zoom via mouse wheel is disabled, scroll on image should allow the page to be scrolled.

**Current Behavior** : When image zoom via mouse wheel is disabled, scroll on image does not lets the page to be scrolled.

**Comment by jpilfold** [comment]
I've made this change and released to npm as part of 1.0.8, let me know if you're happy with the change so we can close this ticket

**Comment by saberrahul** [comment]
Working as expected.
Great work.
