### ISSUE TITLE
Reset Method Should Be Public

### ISSUE THREAD

**Issue by AnthonyNWRI** [jpilfold/ngx-image-viewer#20]
Hi
I'm using your ngx-image-viewer component. It works great except for one small issue. The reset method is private. I am managing a carousel of images and displaying the selected image with the ngx-image-viewer. If the user zooms in or out and then clicks on another image in the carousel, the new image is rendered, but at the zoom level set for the previous image. This is not what I need. If i use the component provided next/previous buttons to navigate the list of images, the component calls reset prior to rendering each new image. This is the behavior i need when i specify the new image index to display. I could get this behavior in my code if the reset() method were made public.
Anthony

**Comment by jpilfold** [comment]
This makes sense. I'll create the change, and publish it this evening

**Comment by AnthonyNWRI** [comment]
Thanks so much!!
Anthony
________________________________

**Comment by jpilfold** [comment]
Okay, I've just published a new version (1.0.11) to npm with this change in there, hope it helps. Let me know if there are any issues.
