### ISSUE TITLE
No icons appear

### ISSUE THREAD

**Issue by sergiomoura** [jpilfold/ngx-image-viewer#21]
I've installed font-awesome, but no icon shows up.

![image](https://user-images.githubusercontent.com/4131912/45638379-643cfa00-ba83-11e8-8148-780e0888846b.png)

I'm using Angular 6.
Is that a problem?

**Comment by jpilfold** [comment]
It shouldn't be an issue using angular 6. Have you made the font awesome CSS available?

**Comment by sergiomoura** [comment]
I haven't made font awesome css avaliable. Thanks!

**Comment by harishreddy-m** [comment]
If some one is here for same reason.
follow instructions from
https://www.npmjs.com/package/angular-font-awesome
