### ISSUE TITLE
Open Image Viewer in fullscreen mode by default

### ISSUE THREAD

**Issue by mirko-lazarevic** [jpilfold/ngx-image-viewer#25]
Hello @jpilfold, I'm using your component dynamically  (I create the component instance when user clicks on the button)  I'd like to know is it possible to open image viewer in fullscreen mode directly?

By default `fullscreen` is set to `false`, so far the only thing I could do is
`this.imageViewerComponentInstance.fullscreen = true;`

**Comment by jpilfold** [comment]
As per the MDN docs (https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen) fullscreen must be called as part of a user action, otherwise it will fail. You could try calling `toggleFullscreen` on the component instance from your button click though

**Comment by mirko-lazarevic** [comment]
I come up with different solution. Thank you very much, anyway.
