### ISSUE TITLE
custom button

### ISSUE THREAD

**Issue by tmburnell** [jpilfold/ngx-image-viewer#4]
I really like this library.  However I was wondering it this enhancement was valid with your design.  

I would like to have a config option for adding a custom button.  I figured on click of the button should either callback or fire an event ... and what ever is hosting it has to do the logic.  

My specific case is I want to add an image to a queue.  I can add the button outside the image viewer however it would look cleaner if it was inside (specially if they are full screen).

**Comment by tmburnell** [comment]
And If this does not fit the design, can we 2-way bind the index?  This way an external button can know what image is actively being viewed.

**Comment by jpilfold** [comment]
I don't have any problems with that in theory. You're second idea may be simpler in fairness, but I guess the first is slightly more flexible.

Are you willing to submit a pull request for this, or would you prefer me to make the change?

**Comment by tmburnell** [comment]
I will try and work on one. Your code base looks pretty easy to work with.

**Comment by tmburnell** [comment]
Can you let me know when you have built it, and have it pushed to npm.  
but I will go ahead and close the ticket.

**Comment by jpilfold** [comment]
Just pushed it up now, so that's ready.

Thanks for contributing
