### ISSUE TITLE
Two way binding of image index.

### ISSUE THREAD

**Issue by tmburnell** [jpilfold/ngx-image-viewer#6]
This is an enhancement.  I am willing to work on the request. 

Add Two way binding to index, so the parent knows what the current selected index is.  

This would allow for possible dynamically changing custom buttons and/or adding action buttons outside the image viewer. 

But point of inquiry first ... the existing input is called index but you had me change customEvents to use imageIndex ... so should we change this too? (it would be a breaking change for people though) 
```javascript
@Input()
  index = 0;
```

**Comment by jpilfold** [comment]
I'd prefer not to introduce breaking changes if it can be avoid

**Comment by tmburnell** [comment]
So do you want this change but without the rename

**Comment by jpilfold** [comment]
Yep, feel free to make the change, just avoid the rename please

**Comment by jpilfold** [comment]
Closing, as this has now been merged into master and published to npm
