### ISSUE TITLE
Support for arrow key navigation

### ISSUE THREAD

**Issue by tmburnell** [jpilfold/ngx-image-viewer#8]
It would be nice to have arrow key support. 
I was trying to think about how to do this and this is what i have come up with:

On mouse over set a flag like `keySupportEnabled`
Then add an event on window listing for arrow keys and our flag, like below: 
```javascript
$(window).keydown(function(e){
    if(e.which === 37 && keySupportEnabled){
       // run nav code
    } else if (e.which === 39 && keySupportEnabled){
       // run nav code
    }
```

Only concern I have is we need to unregister this window even on destroy ... but should be able to add angular onDestroy method for cleanup.

**Comment by jpilfold** [comment]
Don't worry, there's a simpler way of doing this using `@HostListener`, I'll put something together now

**Comment by jpilfold** [comment]
I've just published that up now, can you give it a go please?

**Comment by tmburnell** [comment]
Seems to work correctly, thanks.
